// After Dark — the card deck. 112 cards, 4 heat levels.
// House rules baked in: two players only, nothing anal (a good butt massage
// is not that), everything consensual, Pause button is sacred.
// Text is addressed to the ROLLER. "{P}" = partner's display name.

import type { Card } from "./engine";

export const DECK: Card[] = [
  // ---------------------------------------------------------------- Heat 1: Spark
  { id: "s01", heat: 1, text: "Give {P} your best pickup line as if you just met at a bar tonight. Bad puns encouraged." },
  { id: "s02", heat: 1, text: "Whisper in {P}'s ear the first thing you thought when you saw them today." },
  { id: "s03", heat: 1, text: "Stare into {P}'s eyes. No talking, no touching. First to laugh owes a 10-second kiss.", timerSec: 60, require: { blindfolded: { roller: false, partner: false } } },
  { id: "s04", heat: 1, text: "Slow dance with {P} to no music at all. Cheek to cheek.", timerSec: 30 },
  { id: "s05", heat: 1, text: "Kiss the back of {P}'s hand like royalty. Then the wrist. Then decide how far up the arm royalty goes." },
  { id: "s06", heat: 1, text: "Tell {P} three things about their body you can't stop thinking about. Be specific." },
  { id: "s07", heat: 1, text: "Text {P} something filthy right now, even though they're sitting next to you. Watch their face while they read it." },
  { id: "s08", heat: 1, text: "Trace one fingertip along {P}'s jaw, down the neck, and stop at the collarbone. Slowly.", timerSec: 20 },
  { id: "s09", heat: 1, text: "Truth: describe the exact moment you knew you wanted {P}." },
  { id: "s10", heat: 1, text: "Look {P} up and down, slowly, biting your lip, like you're deciding what to do with them. Say nothing." },
  { id: "s11", heat: 1, text: "Kiss {P}'s cheek dangerously close to the lips. Stay there for three breaths. Do not close the gap." },
  { id: "s12", heat: 1, text: "Compliment what {P} is wearing, then tell them exactly how it's coming off later.", require: { minClothing: { partner: 2 } } },
  { id: "s13", heat: 1, text: "Hold {P}'s face in both hands and give them the softest kiss you're physically capable of." },
  { id: "s14", heat: 1, text: "Play with {P}'s hair while telling them your favorite memory of the two of you.", timerSec: 30 },
  { id: "s15", heat: 1, text: "Truth: confess one fantasy about {P} you've never said out loud. Tonight it's out loud." },
  { id: "s16", heat: 1, text: "Give {P} a hand massage while holding eye contact the whole time.", timerSec: 20, require: { blindfolded: { roller: false, partner: false } } },
  { id: "s17", heat: 1, text: "Whisper what you want to do to {P} tonight using only innocent words. Make it filthy anyway." },
  { id: "s18", heat: 1, text: "Kiss {P}'s neck once. Just once. Make it count." },
  { id: "s19", heat: 1, text: "{P} sits on your lap for the next two rounds. House rule, not negotiable." },
  { id: "s20", heat: 1, text: "Tell {P} the exact thing they do that drives you crazy. The good kind of crazy." },
  { id: "s21", heat: 1, text: "Fingertips only: trace {P}'s arms from shoulders to fingertips and back.", timerSec: 30 },
  { id: "s22", heat: 1, text: "Recreate your very first kiss with {P}, exactly how it happened. Nerves included." },
  { id: "s23", heat: 1, text: "Truth: name one public place you'd risk kissing {P} far too intensely." },
  { id: "s24", heat: 1, text: "Invent a new pet name for {P} based on how they look right now. Use it for the rest of the game." },
  { id: "s25", heat: 1, text: "Forehead to forehead, eyes closed, five slow breaths together. Then one kiss." },
  { id: "s26", heat: 1, wild: true, weight: 5, text: "FREEZE: hold perfectly still, faces 10 cm apart, lips almost touching. Whoever closes the gap loses and owes the winner any one request.", timerSec: 30 },

  // ---------------------------------------------------------------- Heat 2: Tease
  { id: "t01", heat: 2, text: "Remove one item of {P}'s clothing. Slowly. Like unwrapping something expensive.", require: { minClothing: { partner: 1 } }, effects: ["partner-strips-one"] },
  { id: "t02", heat: 2, text: "Take one of your own items off like it's a show. Because it is.", require: { minClothing: { roller: 1 } }, effects: ["roller-strips-one"] },
  { id: "t03", heat: 2, text: "Make out with {P}. Hands stay above the waist. That's the hard part.", timerSec: 60 },
  { id: "t04", heat: 2, text: "Kiss {P} from just under the ear down to the collarbone. Take the long way.", timerSec: 30 },
  { id: "t05", heat: 2, text: "Run an ice cube along {P}'s neck and collarbone until it starts to melt. Follow the trail with your lips." },
  { id: "t06", heat: 2, text: "Give {P} a proper butt massage. Two hands, real technique, take it seriously." },
  { id: "t07", heat: 2, text: "Trace {P}'s stomach with your fingertips, drifting lower each pass, until they make a sound. Then stop completely.", require: { maxClothing: { partner: 2 } } },
  { id: "t08", heat: 2, text: "Undo one button, zipper, or strap on {P}. Teeth get bonus points.", require: { minClothing: { partner: 1 } } },
  { id: "t09", heat: 2, text: "Kiss {P}'s bare shoulder. Then bite it. Gently. Ish.", require: { maxClothing: { partner: 2 } } },
  { id: "t10", heat: 2, text: "Thirty-second lap dance for {P}. Full commitment or it doesn't count.", timerSec: 30 },
  { id: "t11", heat: 2, text: "Take {P}'s hands and place them exactly where you want them. Keep them there.", timerSec: 30 },
  { id: "t12", heat: 2, text: "Massage {P}'s thighs, inner thighs included. Get close. Never quite arrive.", timerSec: 60 },
  { id: "t13", heat: 2, text: "Whisper to {P}, in explicit detail, what you plan to do at the next heat level." },
  { id: "t14", heat: 2, text: "Kiss down {P}'s bare spine, one vertebra at a time.", require: { maxClothing: { partner: 1 } } },
  { id: "t15", heat: 2, text: "Both of you lose one item each. You pick theirs, they pick yours.", require: { minClothing: { roller: 1, partner: 1 } }, effects: ["both-strip-one"] },
  { id: "t16", heat: 2, text: "Ice cube in your mouth. Kiss {P}'s neck until it's gone." },
  { id: "t17", heat: 2, text: "Take {P}'s hand and kiss each fingertip while watching their eyes.", require: { blindfolded: { roller: false } } },
  { id: "t18", heat: 2, text: "Pick a song in your head and grind on {P} to its rhythm. They have to guess the song.", timerSec: 30 },
  { id: "t19", heat: 2, text: "Tell {P} to close their eyes, then kiss three places they won't expect. Eyes stay closed." },
  { id: "t20", heat: 2, text: "Remove one item of {P}'s clothing with your eyes locked on theirs the entire time.", require: { minClothing: { partner: 1 }, blindfolded: { roller: false, partner: false } }, effects: ["partner-strips-one"] },
  { id: "t21", heat: 2, text: "Massage {P}'s chest. Slowly. With intent.", require: { maxClothing: { partner: 1 } } },
  { id: "t22", heat: 2, text: "No kissing allowed: hover your mouth over {P}'s ear and neck, warm breath only.", timerSec: 20 },
  { id: "t23", heat: 2, text: "Truth: point to the exact spot on your body {P} criminally underuses. They get 30 seconds to make it right. Now." },
  { id: "t24", heat: 2, text: "Kiss {P}'s hip bones. Take a slow, scenic route getting there.", require: { maxClothing: { partner: 1 } } },
  { id: "t25", heat: 2, text: "Write a word on {P}'s bare back with one fingertip. Wrong guess: they owe a 10-second kiss anywhere you point.", require: { maxClothing: { partner: 1 } } },
  { id: "t26", heat: 2, text: "Pin {P}'s hands above their head with one hand and kiss them until YOU are satisfied." },
  { id: "t27", heat: 2, text: "Full-body hug, as much skin to skin as currently possible. Move nothing. Feel everything.", timerSec: 30 },
  { id: "t28", heat: 2, wild: true, weight: 5, text: "SPEED ROUND: 20 seconds to kiss every bare patch of skin {P} currently has. Clock starts now.", timerSec: 20 },
  { id: "t29", heat: 2, text: "Flat palm on {P}'s chest. Feel their heartbeat. Now kiss them until you feel it speed up." },
  { id: "t30", heat: 2, text: "Name your favorite non-obvious part of {P}'s body, then spend 30 seconds giving it the attention it deserves.", timerSec: 30 },

  // ---------------------------------------------------------------- Heat 3: Fire
  { id: "f01", heat: 3, text: "Remove another layer from {P}, and kiss every centimeter of new skin as you reveal it.", require: { minClothing: { partner: 1 } }, effects: ["partner-strips-one"] },
  { id: "f02", heat: 3, text: "Kiss your way from {P}'s neck all the way down. Stop just before the destination. Come all the way back up.", require: { maxClothing: { partner: 1 } } },
  { id: "f03", heat: 3, text: "Sixty seconds of your mouth anywhere {P} directs it. They steer. You obey.", timerSec: 60 },
  { id: "f04", heat: 3, text: "Use your hands on {P} exactly the way they love it best, until the next card is drawn.", require: { maxClothing: { partner: 1 }, restrained: { roller: false } } },
  { id: "f05", heat: 3, text: "Go down on {P} for exactly 90 seconds. Then stop. No matter what. Especially if they protest.", timerSec: 90, require: { maxClothing: { partner: 0 } } },
  { id: "f06", heat: 3, text: "Let {P} watch you touch yourself for 30 seconds. They are not allowed to help.", timerSec: 30, require: { blindfolded: { partner: false } } },
  { id: "f07", heat: 3, text: "Choose: your mouth or your hands. {P} receives your choice for a full minute. They get the other one next round.", timerSec: 60, require: { maxClothing: { partner: 1 } } },
  { id: "f08", heat: 3, text: "Lie skin on skin with {P} and move as slowly as two humans possibly can.", timerSec: 60, require: { maxClothing: { roller: 1, partner: 1 } } },
  { id: "f09", heat: 3, text: "Kiss {P} everywhere EXCEPT the three places they most want it. Make it obvious you're skipping them.", require: { maxClothing: { partner: 1 } } },
  { id: "f10", heat: 3, text: "Tell {P}, in explicit detail, exactly what you want them to do to you. They begin immediately." },
  { id: "f11", heat: 3, text: "Oil or lotion, your hands, {P}'s body, minimum 90 seconds. Butt absolutely included.", timerSec: 90, require: { maxClothing: { partner: 1 }, restrained: { roller: false } } },
  { id: "f12", heat: 3, text: "Stand {P} in front of a mirror, you behind them. Your hands go wherever they want. You both watch.", require: { maxClothing: { partner: 1 }, blindfolded: { roller: false, partner: false } } },
  { id: "f13", heat: 3, text: "The slowest kiss of your life: full body pressed together, hands wandering with zero urgency.", timerSec: 60 },
  { id: "f14", heat: 3, text: "{P} lies perfectly still for one minute while you do whatever you like. Moving or making a sound costs them 10 extra seconds.", timerSec: 60, require: { maxClothing: { partner: 1 } } },
  { id: "f15", heat: 3, text: "Only your mouth, everywhere except their lips, for one minute.", timerSec: 60, require: { maxClothing: { partner: 1 } } },
  { id: "f16", heat: 3, text: "Take {P}'s hand and give them the guided tour: show them EXACTLY how you like to be touched." },
  { id: "f17", heat: 3, text: "Edge {P}: build them all the way up, then stop completely and kiss them like nothing happened.", require: { maxClothing: { partner: 1 }, restrained: { roller: false } } },
  { id: "f18", heat: 3, text: "Trace an ice cube down {P}'s chest and stomach. Follow its exact path with your mouth.", require: { maxClothing: { partner: 1 } } },
  { id: "f19", heat: 3, text: "{P} picks the position. You pick the pace. Sixty seconds at YOUR pace. No negotiation.", timerSec: 60, require: { maxClothing: { roller: 1, partner: 1 } } },
  { id: "f20", heat: 3, text: "Narrate everything you're doing to {P} as you do it. Whispered. Play by play. One minute.", timerSec: 60 },
  { id: "f21", heat: 3, text: "Everything off, both of you, one item at a time, taking turns, watching each other. No rushing.", require: { minClothing: { partner: 1 } }, effects: ["both-strip-one"] },
  { id: "f22", heat: 3, text: "Ask {P} one question: faster, slower, softer, or harder? Then deliver exactly that for a full minute.", timerSec: 60 },
  { id: "f23", heat: 3, text: "Kiss and bite {P}'s inner thighs until they try to pull you where they want you. Resist twice. Then give in.", require: { maxClothing: { partner: 1 } } },
  { id: "f24", heat: 3, text: "Mouth on {P}'s chest, hand somewhere else entirely. Multitasking is a love language.", timerSec: 60, require: { maxClothing: { partner: 1 }, restrained: { roller: false } } },
  { id: "f25", heat: 3, wild: true, weight: 5, text: "SWITCH: whatever was about to happen, {P} now does it to you instead. If nothing was happening, they choose. Anything." },
  { id: "f26", heat: 3, text: "Tell {P} which card tonight got to you the most. Then reenact it with the volume turned all the way up." },
  { id: "f27", heat: 3, text: "Spoon {P}, hands free to roam. They are not allowed to turn around.", timerSec: 90, require: { maxClothing: { partner: 1 } } },
  { id: "f28", heat: 3, wild: true, weight: 5, text: "NO HANDS: for the next two minutes, whatever happens, neither of you may use hands. Improvise.", timerSec: 120 },

  // ---------------------------------------------------------------- Heat 4: Ember
  { id: "e01", heat: 4, text: "Blindfold {P}. It stays on until the dice decides otherwise.", require: { blindfolded: { partner: false } }, effects: ["blindfold-partner"] },
  { id: "e02", heat: 4, weight: 16, text: "Take {P}'s blindfold off. Make sure the first thing they see was worth the wait.", require: { blindfolded: { partner: true } }, effects: ["unblindfold-partner"] },
  { id: "e03", heat: 4, text: "While {P} is blindfolded: touch them with three different things (fabric, ice, lips, fingertips...). They guess each one. Wrong guesses earn a spank.", require: { blindfolded: { partner: true } } },
  { id: "e04", heat: 4, text: "Spank {P} once, exactly as hard as you both like it. If they say \"again\", you may. Once." },
  { id: "e05", heat: 4, text: "Tie {P}'s wrists with something soft (a tie, a robe belt). They stay tied.", require: { restrained: { partner: false } }, effects: ["restrain-partner"] },
  { id: "e06", heat: 4, weight: 16, text: "Untie {P}. Kiss their wrists like an apology you don't mean.", require: { restrained: { partner: true } }, effects: ["release-partner"] },
  { id: "e07", heat: 4, text: "{P} is tied and at your mercy for 90 seconds. They can beg. Begging changes nothing.", timerSec: 90, require: { restrained: { partner: true } } },
  { id: "e08", heat: 4, text: "A fistful of {P}'s hair, at the root, firm not sharp. Pull their head back and kiss them roughly." },
  { id: "e09", heat: 4, text: "Ice on {P}'s nipples until they gasp. Your warm mouth immediately after.", require: { maxClothing: { partner: 1 } } },
  { id: "e10", heat: 4, text: "Bite {P} where the neck meets the shoulder. Hard enough to remember. Soft enough to hide. Maybe." },
  { id: "e11", heat: 4, text: "Give {P} three commands. They obey all three, no questions asked. Keep them achievable and filthy." },
  { id: "e12", heat: 4, text: "{P} may not make a single sound for the next two minutes while you do your worst. Every sound earns a spank. Count them.", timerSec: 120 },
  { id: "e13", heat: 4, text: "Edge {P} twice in a row. Deny both. If they say \"please\", it becomes three.", require: { maxClothing: { partner: 1 }, restrained: { roller: false } } },
  { id: "e14", heat: 4, text: "Low-temp candle if you have one: drip wax slowly on {P}'s back or chest. No candle? 30 seconds of nails down their back instead.", require: { maxClothing: { partner: 1 } } },
  { id: "e15", heat: 4, text: "Pin {P} down with your full body weight and take exactly what you want.", require: { restrained: { roller: false } } },
  { id: "e16", heat: 4, text: "Until the heat changes, {P} addresses you only as \"Sir\" or \"Madam\" (you pick). Enforce it." },
  { id: "e17", heat: 4, text: "Kiss {P} hard with your hand firm on their jaw, tilting their head exactly where you want it." },
  { id: "e18", heat: 4, text: "Order {P} to strip one item for you. You sit. You watch. You critique like an Olympic judge.", require: { minClothing: { partner: 1 } }, effects: ["partner-strips-one"] },
  { id: "e19", heat: 4, text: "Bend {P} over and deliver one spank for every item of clothing they've lost tonight. Count each one out loud." },
  { id: "e20", heat: 4, text: "{P} holds one position of your choosing for 60 seconds while you do whatever you please. If they break the pose, the clock restarts.", timerSec: 60 },
  { id: "e21", heat: 4, text: "Nails down {P}'s bare back, shoulder blades to lower back, slow. Leave a story.", require: { maxClothing: { partner: 1 } } },
  { id: "e22", heat: 4, text: "For the next three rounds, {P} must ask permission before doing anything. Deny at least one request. Enjoy it." },
  { id: "e23", heat: 4, text: "Hold both of {P}'s wrists in one hand. The other hand does whatever it wants for one minute.", timerSec: 60, require: { restrained: { partner: false, roller: false } } },
  { id: "e24", heat: 4, text: "Whisper the single filthiest sentence you have in you into {P}'s ear. If you laugh, they get to spank you." },
  { id: "e25", heat: 4, text: "Torture by slowness: 90 seconds SO slow it hurts. If {P} pushes for more, the clock restarts. Tell them the rule first.", timerSec: 90 },
  { id: "e26", heat: 4, wild: true, weight: 5, text: "ROLE SWAP: whoever has been in charge tonight kneels. The other takes over completely until the next wild card." },
  { id: "e27", heat: 4, wild: true, weight: 5, text: "RED LIGHT: for two minutes you do what you want, but when {P} says \"red\", you freeze mid-motion for 10 full seconds. Then continue.", timerSec: 120 },
  { id: "e28", heat: 4, text: "Aftercare preview: stop everything. Wrap {P} up in your arms, 30 seconds of the softest touch you own, one genuine compliment. Then back to business.", timerSec: 30 },
];
