// One-shot: fetch real TMDB poster paths for every title in lib/mock-data.ts
// and write them to lib/posters.ts. Run: node scripts/fetch-posters.mjs
// Needs TMDB_READ_TOKEN (read from .env.local if not in the environment).
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

// load token from env or .env.local
let token = process.env.TMDB_READ_TOKEN;
if (!token) {
  try {
    const env = readFileSync(join(root, ".env.local"), "utf8");
    token = env.match(/^TMDB_READ_TOKEN=(.+)$/m)?.[1]?.trim();
  } catch {}
}
if (!token) {
  console.error("No TMDB_READ_TOKEN found.");
  process.exit(1);
}

const src = readFileSync(join(root, "lib/mock-data.ts"), "utf8");
// match: id: "tv:46648", tmdbId: 46648, mediaType: "tv"
const re = /id:\s*"([^"]+)",\s*tmdbId:\s*(\d+),\s*mediaType:\s*"(movie|tv)"/g;
const items = [...src.matchAll(re)].map((m) => ({ id: m[1], tmdbId: Number(m[2]), media: m[3] }));
console.log(`Found ${items.length} titles. Fetching posters…`);

const map = {};
for (const it of items) {
  try {
    const res = await fetch(`https://api.themoviedb.org/3/${it.media}/${it.tmdbId}?language=en-US`, {
      headers: { Authorization: `Bearer ${token}` },
    });
    const data = await res.json();
    if (data.poster_path) {
      map[it.id] = data.poster_path;
      console.log(`  ✓ ${it.id}  ${data.poster_path}`);
    } else {
      console.log(`  – ${it.id}  (no poster)`);
    }
  } catch (e) {
    console.log(`  ! ${it.id}  ${e.message}`);
  }
}

const out =
  "// AUTO-GENERATED by scripts/fetch-posters.mjs — real TMDB poster paths.\n" +
  "// Re-run that script to refresh. Used by lib/mock-data.ts.\n" +
  "export const POSTERS: Record<string, string> = " +
  JSON.stringify(map, null, 2) +
  ";\n";
writeFileSync(join(root, "lib/posters.ts"), out);
console.log(`\nWrote lib/posters.ts with ${Object.keys(map).length} posters.`);
